return {
  "nvim-treesitter/nvim-treesitter",
  event = { "BufReadPre", "BufNewFile" },
  build = ":TSUpdate",
  config = function()
    require("nvim-treesitter.configs").setup {
      ensure_installed = {
        "bash",
        "c",
        "css",
        "diff",
        "fish",
        "html",
        "javascript",
        "jsdoc",
        "json",
        "json5",
        "jsonc",
        "lua",
        "luadoc",
        "luap",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "ruby",
        "rust",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "vue",
        "yaml",
        "dockerfile",
        "go",
        "lua",
        "sql",
        "javascript",
        "typescript",
        "markdown",
        "markdown_inline",
        "gomod",
        "gosum",
        "proto",
      },
      highlight = { enable = true },
      indent = { enable = true },
    }
  end,
}
